[tool.poetry]
name = "ml"
version = "0.1.0"
description = ""
authors = ["icoding2016 <icoding2016@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.1.1"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
