# Generated by Django 3.2.7 on 2021-09-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('handle_time', models.DateTimeField()),
            ],
        ),
    ]
